### ISSUE TITLE
Komporcoin

### ISSUE THREAD

**Issue by komporcoin** [ghostlander/nsgminer#10]

**Comment by ghostlander** [comment]
What's your issue?

**Comment by komporcoin** [comment]
Please help me to make my own cryptocoin

**Comment by ghostlander** [comment]
If you need help with coin creation, please email me or send a message on Facebook.

**Comment by komporcoin** [comment]
If I can know what your Facebook name or your email

**Comment by ghostlander** [comment]
ghostlander at gmail dot com
