### ISSUE TITLE
Failed to load OpenCL library, no GPUs usable

### ISSUE THREAD

**Issue by mburknoe** [ghostlander/nsgminer#13]
Hey guys, I just compiled this and it's saying that it can't load OpenCL, I tried installing opencl with apt but I'm not sure I did it correctly. Does anyone know what's missing?

apt install nvidia-libopencl1-375
```

root@SDC-R091-DWN-001:/home/root/nsgminer# ./nsgminer -n
[2017-09-28 15:46:39] Failed to load OpenCL library, no GPUs usable                    
[15:46:39] 0 OpenCL GPU devices detected
                    
[15:46:39] Unable to load the AMD Display Library                    
[15:46:39] NVML found 4 devices:                    
[15:46:39] GPU 0: GeForce GTX 970 [0000:06:00.0]
                    
[15:46:39] GPU 1: GeForce GTX 970 [0000:07:00.0]
                    
[15:46:39] GPU 2: GeForce GTX 1070 [0000:08:00.0]
                    
[15:46:39] GPU 3: GeForce GTX 970 [0000:0B:00.0]


root@SDC-R091-DWN-001:~# nvidia-smi  | grep Driver
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |    |

```

**Comment by ghostlander** [comment]
Not sure about packages of your Linux distro, but something like nvidia-375-dev could be missing. Another option is to download and install NVIDIA-Linux-x86_64-384.69.run or whatever is the latest. It just works.

**Comment by teshy** [comment]
Same issue as OP 
export DISPLAY=:0
marco@compaq:~/Downloads/nsgminer$ ./nsgminer -n
[2017-11-03 19:28:55] Failed to load OpenCL library, no GPUs usable                    
[19:28:55] 0 OpenCL GPU devices detected
                    
[19:28:55] NVML found 4 devices:                    
[19:28:55] GPU 0: GeForce GTX 1070 [0000:03:00.0]                    
[19:28:55] GPU 1: GeForce GTX 1070 [0000:04:00.0]                    
[19:28:55] GPU 2: GeForce GTX 1060 6GB [0000:05:00.0]                    
[19:28:55] GPU 3: GeForce GTX 1070 [0000:06:00.0]           

| NVIDIA-SMI 384.90                 Driver Version: 384.90

**Comment by ghostlander** [comment]
Short answer. Are you sure that you have OpenCL installed? Is libOpenCL.so available for linking?

Long answer. Put the following code into clquery.cpp, place into your NSGminer source directory, compile with "g++ -O2 -o clquery -I. clquery.cpp -lOpenCL" and run it.

https://gist.github.com/ghostlander/8e8ea74176539042bcdcf0290a57274b

If it detects your GPUs with "TEST PASSED", NSGminer also will.

**Comment by teshy** [comment]
Thanks this gets me:

/usr/bin/ld: cannot find -lOopenCL
collect2: error: ld returned 1 exit status

I searched for what package I may be missing but came up with nothing, any hints?
On Centos 7.3

**Comment by ghostlander** [comment]
It's -lOpenCL with a single 'O'.

**Comment by teshy** [comment]
nOoob mistake, 

Thanks, this issue was I was missing opencl-headers and had to reboot.

yum install opencl-headers
reboot

**Comment by jruillier** [comment]
Same problem solved on Ubuntu with 
`sudo apt install nvidia-opencl-dev`

**Comment by jsanderton** [comment]
I have same problem and the clquery gives "TEST PASSED"
nsgminer -c nsgminer.conf gives this "All devices disabled, cannot mine!"
nsgminer -c nsgminer.conf -neoscrypt gives this 
[2018-01-14 12:13:20] Failed to load OpenCL library, no GPUs usable                    
[12:13:20] 0 OpenCL GPU devices detected
                    
[12:13:20] GPU 0 iAdapterIndex 0 strUDID 256:26808:4098:836:4163 iBusNumber 1 iDeviceNumber 0 iFunctionNumber 0 iVendorID 4098 strAdapterName  AMD Radeon HD 5700 Series                     
[12:13:20] ADL found more devices than opencl!                    
[12:13:20] There is possibly at least one GPU that doesn't support OpenCL                    
[12:13:20] Use the gpu map feature to reliably map OpenCL to ADL                    
[12:13:20] WARNING: Number of OpenCL and ADL devices did not match!                    
[12:13:20] Hardware monitoring may NOT match up with devices!                    
[12:13:20] Unable to load the NVIDIA Management Library  

clquery result
clDeviceQuery Starting...

1 OpenCL Platforms found

 CL_PLATFORM_NAME: 	AMD Accelerated Parallel Processing
 CL_PLATFORM_VERSION: 	OpenCL 2.0 AMD-APP (1800.11)
OpenCL Device Info:

 2 devices found supporting OpenCL on: AMD Accelerated Parallel Processing

 ----------------------------------
 Device Juniper
 ---------------------------------
  CL_DEVICE_NAME: 			Juniper
  CL_DEVICE_VENDOR: 			Advanced Micro Devices, Inc.
  CL_DRIVER_VERSION: 			1800.11
  CL_DEVICE_TYPE:			CL_DEVICE_TYPE_GPU
  CL_DEVICE_MAX_COMPUTE_UNITS:		10
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:	256 / 256 / 256 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:	256
  CL_DEVICE_MAX_CLOCK_FREQUENCY:	850 MHz
  CL_DEVICE_ADDRESS_BITS:		32
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:		128 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:		512 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
  CL_DEVICE_LOCAL_MEM_TYPE:		local
  CL_DEVICE_LOCAL_MEM_SIZE:		32 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:		1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:	128
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	8

  CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 16384
					2D_MAX_HEIGHT	 16384
					3D_MAX_WIDTH	 2048
					3D_MAX_HEIGHT	 2048
					3D_MAX_DEPTH	 2048
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 16, SHORT 8, INT 4, FLOAT 2, DOUBLE 4


 ----------------------------------
 Device Intel(R) Celeron(R) CPU        E3400  @ 2.60GHz
 ---------------------------------
  CL_DEVICE_NAME: 			Intel(R) Celeron(R) CPU        E3400  @ 2.60GHz
  CL_DEVICE_VENDOR: 			GenuineIntel
  CL_DRIVER_VERSION: 			1800.11 (sse2)
  CL_DEVICE_TYPE:			CL_DEVICE_TYPE_CPU
  CL_DEVICE_MAX_COMPUTE_UNITS:		2
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:	1024 / 1024 / 1024 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:	1024
  CL_DEVICE_MAX_CLOCK_FREQUENCY:	2600 MHz
  CL_DEVICE_ADDRESS_BITS:		32
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:		1024 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:		2012 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
  CL_DEVICE_LOCAL_MEM_TYPE:		global
  CL_DEVICE_LOCAL_MEM_SIZE:		32 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:		1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:	128
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	64

  CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 8192
					2D_MAX_HEIGHT	 8192
					3D_MAX_WIDTH	 2048
					3D_MAX_HEIGHT	 2048
					3D_MAX_DEPTH	 2048
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 16, SHORT 8, INT 4, FLOAT 2, DOUBLE 4


clDeviceQuery, Platform Name = AMD Accelerated Parallel Processing, Platform Version = OpenCL 2.0 AMD-APP (1800.11), NumDevs = 2, Device = Juniper, Device = Intel(R) Celeron(R) CPU        E3400  @ 2.60GHz

System Info: 

 Local Time/Date =  12:10:58, 01/14/2018
 CPU Name: Intel(R) Celeron(R) CPU E3400 @ 2.60GHz 
 number of CPU processors: 2
 Linux version 3.2.0-121-generic (buildd@lcy01-31) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #164-Ubuntu SMP Wed Jan 11 15:13:59 UTC 2017


TEST PASSED
