### ISSUE TITLE
nsgminer.exe  :  LINK  ERROR

### ISSUE THREAD

**Issue by cqtenq** [ghostlander/nsgminer#14]
CCLD   nsgminer.exe
f:\Coin\FTC\miner3\nsgminer-master/miner.c:6953: undefined reference to `nanosleep'
f:\Coin\FTC\miner3\nsgminer-master/api.c:3620: undefined reference to `pthread_getclean'

**Comment by ghostlander** [comment]
Your compiler lacks these calls obviously. You need to patch either it or the miner.
