### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by dstana** [ghostlander/nsgminer#20]
Getting this error after running autogen.sh

In file included from miner.c:69:
neoscrypt.h:9: error: redefinition of typedef ‘ullong’
miner.h:35: note: previous declaration of ‘ullong’ was here
neoscrypt.h:12: error: redefinition of typedef ‘uchar’
miner.h:31: note: previous declaration of ‘uchar’ was here
make[2]: *** [nsgminer-miner.o] Error 1

**Comment by ghostlander** [comment]
Your build environment?

**Comment by ghostlander** [comment]
Fixed in https://github.com/ghostlander/nsgminer/commit/9c58c792c955c70a3c3d904484ce4f9f1c0506ae
