### ISSUE TITLE
worksize does not change in 0.9.4

### ISSUE THREAD

**Issue by gregfromo** [ghostlander/nsgminer#24]
I tried to play with worksize -w 256 but it's using allways 128, as I can see from the resulting .bin file.
In 0.9.3 a change to -w 256 produced error, but .bin

Win 10, x64, blockchaindrivers August, RX580

**Comment by ghostlander** [comment]
-w 256 doesn't work with the default NeoScrypt kernel, therefore it gets reduced to -w 128 in order to avoid a compilation error. -w 256 works with the VLIW kernels.

See https://github.com/ghostlander/nsgminer/commit/f924288eb8e3978c893c8b7dd3d83830e8947578
