### ISSUE TITLE
Address offset exceeds variable size

### ISSUE THREAD

**Issue by anddmx** [ghostlander/nsgminer#26]
All I get is the below error. What am I doing wrong?

```
[16:28:48] Probing for an alive pool
[16:28:49] The network difficulty has been set to 421428
[16:28:49] Stratum from pool 0 detected new block
[16:28:49] Pool 0 is sending mismatched block contents to us (0 is not 1-1)
[16:28:49] The network difficulty has been set to 2836419
[16:28:49] Stratum from pool 0 detected new block
[16:28:49] Pool 0 is sending mismatched block contents to us (0 is not 1-1)Error in hsa_operand section, at offset 3552:
                                        Address offset exceeds variable size
                                                                            LLVM ERROR:
         Brig container validation has failed in BRIGAsmPrinter.cpp
```

./nsgminer --neoscrypt -g 1 -w 256 -I 16 -o stratum+tcp://pool.cryptopros.us:4233 -u walletaddress -p x

**Comment by ghostlander** [comment]
You have to specify a coin to mine. Autoswitching between coins isn't supported.

**Comment by edsonayllon** [comment]
Hello, I'm having the same issue. 

Pool 0 is sending mismatched block contents to us (0 is not 4-7)

I specified the coin in the password, as the pool specified.  

-p c=CRC

Is there a way to specify the coin in the miner?

**Comment by anddmx** [comment]
I have changed the command line password parameter, but still getting the same error.

./nsgminer -g 1 -w 256 -I 16 -o stratum+tcp://pool.cryptopros.us:4233 -u walletaddress -p c=GBX

**Comment by ghostlander** [comment]
I suggest to try another pool.

**Comment by anddmx** [comment]
I did. Same error. Looks like I won't be mining neoscrypt anytime soon. Unless I use windows....

./nsgminer -k neoscrypt  -g 1 -w 256 -I 16 -o stratum+tcp://pool.bsod.pw:4233 -u CQAQwsE5JQsgcd7jKMtrofyfgAz9Kf7fNd -p c=CRC

Guess I'm out of lucky on this one.

Thanks for you help.

**Comment by ghostlander** [comment]
Another pool doesn't mean another multipool.

**Comment by anddmx** [comment]
Sorry, I did try another non-multi pool and I get the same error.

./nsgminer --neoscrypt -g 1 -w 256 -I 16 -o stratum+tcp://stratum.aikapool.com:7905 -O test.test:test

**Comment by edsonayllon** [comment]
All the available pools for the coins I am trying to mine are multipools

**Comment by edsonayllon** [comment]
@anddmx That pool is a multipool

**Comment by anddmx** [comment]
That only pools I can find.
