### ISSUE TITLE
NSGMiner Freezes

### ISSUE THREAD

**Issue by korishan** [ghostlander/nsgminer#32]
I'm using MultiPoolMiner to do batch mining and such. That program works really well. My problem currently is with nsgminer specifically.
NSGminer keeps freezing. I get no text in the miner. I even tried to use the mouse to do a "quick edit" mode and select the screen to see if anything was there. Nope, no text at all.
Log file MPM shows:
>2018-01-28 22:42:45 INFO: Starting AMD miner NsgminerAmd: 'C:\Mining\MultiPoolMiner\Bin\Nsgminer\nsgminer.exe --api-port 14028 --api-listen --neoscrypt -o stratum+tcp://neoscrypt.usa.nicehash.com:3341 -u 3JQbSU8asbq4gwhgQAbW7yrEivvxoFY44m.multipoolminer2 -p x --gpu-threads 1 --worksize 64 --intensity 15 --gpu-platform 0'
>....
>2018-01-28 22:43:20 ERROR: Failed to connect to miner (NsgminerAmd). 
>2018-01-28 22:43:21 INFO: Starting next run...
>...
>2018-01-28 22:44:25 ERROR: Failed to connect to miner (NsgminerAmd). 
>2018-01-28 22:44:25 INFO: Starting next run...
>...
> 2018-01-28 22:45:31 ERROR: Failed to connect to miner (NsgminerAmd). 
> 2018-01-28 22:45:32 INFO: Starting next run...

When it freezes like that, I can select the window and press "any key" and it'll close. However, when it's frozen, MPM won't close it and start another miner.

The NSGMiner that is running is the version that MPM downloaded during first run.

>PS C:\Mining\MultiPoolMiner\Bin\Nsgminer> .\nsgminer.exe -V
>nsgminer 0.9.4

Thoughts, Suggestions, Ideas?????

Kori

**Comment by ghostlander** [comment]
It doesn't work with multipools. You have to stick to a particular coin.
