### ISSUE TITLE
Bunch of ADL errors, crashing and won't start

### ISSUE THREAD

**Issue by kyleboddy** [ghostlander/nsgminer#33]
![image](https://user-images.githubusercontent.com/746351/35775960-49536c2a-0948-11e8-97ad-213773044219.png)

Can't tell exactly which errors are causing the fatal crash. Trying to suppress the ADL and Nvidia errors with the `--no-adl` and `--no-nvml` switches, but that doesn't seem to be working. 

It's a bunch of RX550s installed in the board. Works fine with `xmr-stak`. Thanks for any help you can give.

**Comment by kyleboddy** [comment]
Runnig 12/17/2017 drivers from AMD, BTW.

Here's the code not in image form:

> 
> C:\Users\Janus\Desktop\nsgminer-win64-0.9.4>nsgminer.exe -neoscrypt -o stratum+tcp://neoscrypt.mine.ahashpool.com:4233 -u 13AY5xE73BWokBJkSo8tSN4UexhT7W3hEU -p ID=Janus,c=BTC --gpu-platform 0 --no-adl --no-nvml
> [2018-02-04 01:10:18] OpenCL platform 0 vendor: Advanced Micro Devices, Inc.
> [01:10:18] OpenCL platform 0 name: AMD Accelerated Parallel Processing
> [01:10:18] OpenCL platform 0 version: OpenCL 2.1 AMD-APP (2527.7)
> [01:10:18] Platform 0 devices: 12
> [01:10:18]      0       gfx804
> [01:10:18]      1       gfx804
> [01:10:18]      2       gfx804
> [01:10:18]      3       gfx804
> [01:10:18]      4       gfx804
> [01:10:18]      5       gfx804
> [01:10:18]      6       gfx804
> [01:10:18]      7       gfx804
> [01:10:18]      8       gfx804
> [01:10:18]      9       gfx804
> [01:10:18]      10      gfx804
> [01:10:18]      11      gfx804
> 
> [01:10:18] OpenCL platform 1 vendor: Intel(R) Corporation
> [01:10:18] OpenCL platform 1 name: Intel(R) OpenCL
> [01:10:18] OpenCL platform 1 version: OpenCL 2.1
> [01:10:18] Platform 1 devices: 1
> [01:10:18]      0       Intel(R) HD Graphics 630
> 
> [01:10:18] 13 OpenCL GPU devices detected
> 
> [01:10:19] Failed to ADL_Adapter_ID_Get. Error -5
> [01:10:19] ADL found more devices than opencl!
> [01:10:19] There is possibly at least one GPU that doesn't support OpenCL
> [01:10:19] Use the gpu map feature to reliably map OpenCL to ADL
> [01:10:19] Failed to ADL_Adapter_ID_Get. Error -5
> [01:10:19] WARNING: Number of OpenCL and ADL devices did not match!
> [01:10:19] Hardware monitoring may NOT match up with devices!
> [01:10:19] GPU 0 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 1 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 2 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 3 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 4 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 5 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 6 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 7 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 8 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 9 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 10 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] GPU 11 Radeon RX 550 Series hardware monitoring enabled
> [01:10:19] Failed to ADL_Overdrive5_ODPerformanceLevels_Get
> [01:10:19] Unable to load the NVIDIA Management Library

**Comment by kyleboddy** [comment]
Never mind, fixed because I'm a moron. Put the double-switch options ahead of the single switch ones otherwise they are ignored.

**Comment by mazoku89** [comment]
Hey @kyleboddy ,

I'm having this issue too. I can't get any double switch to be accepted. Can you show me what you bat file looks like?
