### ISSUE TITLE
Scan and Expiry params

### ISSUE THREAD

**Issue by goodthebest** [ghostlander/nsgminer#36]
I’m little confused between these two, what Scan and Expiry options really are in NSGminer and what are optimal values in case of solo miner? Default set to 60 and 120 for scan and expiry respectively.

And what does it mean: **Successfully rolled extranonce to dataid** ?

**Comment by ghostlander** [comment]
These options are useful for GetWork solo mining with no long polling or Stratum present for new block notifications.

Extranonce is used to rebuild the coin base / merkle root if the miner runs out of nonce range.
