### ISSUE TITLE
AMD ADL Library / Thus I cant set higher intensity

### ISSUE THREAD

**Issue by d0n-miner1** [ghostlander/nsgminer#37]
Hey John.

Been following your work for quite a while now.
Detailed and I like reading because you actually do explain why.
Thank you for all your work these while. 
Tried to download the ccminer version for neoscrypt, but i guessed you've archived it.

This is my current issue now.
Since the GPU couldnt read from the ADL Library, all the info's are wrong.

 

> -------------------------------------------------------------------------------
 ALL 53s:346.8 avg:351.2 u:338.5 KH/s | A:144 R:6 S:0 HW:0 WU:19.37/m
 ST:2  DW:16  GW:9  LW:210  GF:0  NB:2  AS:0  RF:0  E:30.10
 Connected to neoscrypt.eu1.unimining.net diff 6 with stratum as GTqPii9tdbT74ChhGo2HM4W5d3uffEPSVP
 Block: 0x00000000017183EC... [07:11:07]  Diff:519K  Best:51
--------------------------------------------------------------------------------
 [P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
 OCL  0:                |  52.8  49.0  28.2 KH/s | A:2 R:0 HW:0 U: 0.3/m
 OCL  1:                |  26.3  28.3  56.4 KH/s | A:4 R:0 HW:0 U: 0.5/m
 OCL  2:                |  26.2  28.6  28.2 KH/s | A:2 R:0 HW:0 U: 0.3/m
 OCL  3:                |  26.3  28.6  18.8 KH/s | A:2 R:0 HW:0 U: 0.3/m
 OCL  4:                |  25.1  27.2  51.7 KH/s | A:4 R:0 HW:0 U: 0.5/m
 OCL  5:                |  25.2  27.3  14.1 KH/s | A:1 R:0 HW:0 U: 0.1/m
 OCL  6:                |  25.8  28.0   0.0 KH/s | A:0 R:0 HW:0 U: 0.0/m
 OCL  7:                |  25.2  27.2   0.0 KH/s | A:0 R:0 HW:0 U: 0.0/m
 OCL  8:                |  25.1  27.2  28.2 KH/s | A:2 R:1 HW:0 U: 0.3/m
 OCL  9:                |  25.2  27.2  37.6 KH/s | A:3 R:0 HW:0 U: 0.4/m
 OCL 10:                |  26.2  28.4  28.2 KH/s | A:2 R:0 HW:0 U: 0.3/m
 OCL 11:                |  26.0  28.0  23.5 KH/s | A:2 R:0 HW:0 U: 0.3/m
 OCL 12:                |  26.2  28.3  23.5 KH/s | A:2 R:0 HW:0 U: 0.3/m
--------------------------------------------------------------------------------

[07:11:07] The network difficulty has been set to 518524
[07:11:07] New block 0x00000000017183EC diff 519K
[07:11:07] Stratum from pool 0 detected new block

hahahha.
Not even sure if it is mining.
1, the GPU is way to quiet compared to when i mine with Claymore.
2. cant increase intensity
3. not sure the hashrates are accurate.

Can you help me here please?
I am using AMD's 13 GPU rig.
Ubuntu distro.
17.30**** driver (amdgpu-pro installed with compute/--px)
has APP-ADL-SDK 3.0

hope you can help me out here. 
im a noob in unix.
but im starting to love it.
and i am just searching for my NVIDIA rig of 8 GPU to mine Cryptonights/Neoscrypts all other algos

Thank you in advance sir.
cheers.

**Comment by ghostlander** [comment]
CCminer has been replaced with CUDAminer: https://github.com/ghostlander/cudaminer-neoscrypt

The maximum intensity is set on a start-up. The memory is allocated accordingly. The intensity can be reduced and increased back later if necessary.

There are accepted shares, so the miner works. There is no ADL support in amdgpu-pro. You have to use third party tools to set clock and fan speeds.

**Comment by d0n-miner1** [comment]
ah i there;s none for AMD gpus?

sad to say i got a mean as 18 gpu rig i would like to try and get some neos and scrypts algo coins.. 

:(

**Comment by d0n-miner1** [comment]
so i need to install the dependencies first like CUDA and all...
are there any instructions available?

thanks alot for this John

**Comment by d0n-miner1** [comment]
i just read. 
A little.
It says if i had installed 390 Nvidia driver, i gotta remove it first then i can install CUDA.
Is this right?

**Comment by ghostlander** [comment]
Install CUDA 6.5 or 7.5 while keeping your existing driver.
