### ISSUE TITLE
fatal: clone of 'git://github.com/luke-jr/X6000_ztex_comm4.git'

### ISSUE THREAD

**Issue by jlsam** [ghostlander/nsgminer#40]
Submodule 'bitstream/ZtexBTCMiner' (git://github.com/luke-jr/ZtexBTCMiner.git) registered for path 'bitstreams/src/ZtexBTCMiner'
Cloning into 'bitstreams/src/X6000_ztex_comm4'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out
github.com[1: 192.30.253.113]: errno=Connection timed out

fatal: clone of 'git://github.com/luke-jr/X6000_ztex_comm4.git' into submodule path 'bitstreams/src/X6000_ztex_comm4' failed

**Comment by ghostlander** [comment]
Looks like a connection problem for you. These submodules are only needed for some SHA-256d FPGAs, so you can ignore them for NeoScrypt.

env NOSUBMODULES=1 ./autogen.sh

**Comment by jlsam** [comment]
But I was able to clone *your* repo... like this:
git clone https://github.com/ghostlander/nsgminer.git

And I can ping those 2 IPs
ping 192.30.253.112
PING 192.30.253.112 (192.30.253.112) 56(84) bytes of data.
64 bytes from 192.30.253.112: icmp_seq=1 ttl=45 time=134 ms
64 bytes from 192.30.253.112: icmp_seq=2 ttl=45 time=134 ms

 ping 192.30.253.113
PING 192.30.253.113 (192.30.253.113) 56(84) bytes of data.
64 bytes from 192.30.253.113: icmp_seq=1 ttl=45 time=149 ms
64 bytes from 192.30.253.113: icmp_seq=2 ttl=45 time=149 ms

Does git:// not use port 80 or 443?
