### ISSUE TITLE
broken link to AMD SDK in Readme.md

### ISSUE THREAD

**Issue by jlsam** [ghostlander/nsgminer#41]
http://developer.amd.com/tools/heterogeneous-computing/amd-accelerated-parallel-processing-app-sdk/

404
OOPS! PAGE NOT FOUND ...

I'm running with the blockchain drivers... SDK is necessary?

**Comment by ghostlander** [comment]
The miner comes with the OpenCL headers needed at compile time. They may be updated with those from a newer SDK, but not really necessary.

The archived versions of the AMD APP SDK: https://github.com/ghostlander/AMD-APP-SDK
