### ISSUE TITLE
can you compile on classic *BSD?

### ISSUE THREAD

**Issue by dchmelik** [ghostlander/nsgminer#43]
This isn't an issue so much as a question I've already investigated a bit.  I'm wondering if you can compile nsgminer on classic *BSD Unix (NetBSD, FreeBSD, OpenBSD.)  I tried last year on FreeBSD but got errors, which, if the developers are willing to try to make sure it can be ported, I'll boot back in and get a compilation log to post.

**Comment by ghostlander** [comment]
AMD doesn't support any *BSD distribution with their proprietary OpenCL capable drivers. Only Linux. NVIDIA supports both Linux and FreeBSD with their proprietary drivers, but most people use CUDA miners with their cards. Open source OpenCL capable drivers currently cannot match performance of proprietary drivers unfortunately. So, while it's a good idea to add support for the *BSD distributions, this task has no practical purpose right now.

**Comment by dchmelik** [comment]
Alright.  Various *BSD is working on it and might support more such drivers soon, and have part of it but I guess not all of it, except under Linux emulation, which is a different issue.  We can close this for now.
