### ISSUE TITLE
installation or running puts extra stuff in /usr/local/bin

### ISSUE THREAD

**Issue by dchmelik** [ghostlander/nsgminer#44]
The ‘make install’ step, or (after it installs it in /usr/local/bin) running nsgminer seems to put a lot of extra stuff in /usr/local/bin a user or programmer normally wouldn't use, like .cl files only for the miner, and various other scripts without extensions but are only for the miner.  Isn't there already a /usr/local/lib/nsgminer that these need to stay in instead, rather than cluttering up people's /usr/local/bin with lots of extra files they don't know what are there for?

**Comment by ghostlander** [comment]
It isn't required to do 'make install' in order to run nsgminer. You can run it in the build directory.

**Comment by dchmelik** [comment]
I feel I was told before for nsgminer or something similar, so wrote & use wrapper shell script (below) so user can place build directory such as in ‘/usr/local/lib/nsgminer,’ have the wrapper run from /usr/local/bin (usually in POSIX-based $PATH.)

That was after something such as './configure --prefix=/usr/local/bin && make && make install DESTDIR=/usr/local' still put too much stuff in /usr/local/bin .  It's always _good_ when a program can support those arguments/flags/switches, but if not, it's probably important to have an explanation/suggestion how to setup/install, and perhaps in this case, wrapper script (if I had to copyright mine, I'd use a shortest-clause BSD-style license used like at SlackBuilds, but I consider this too short to do so, but can be considered a GPL3 (ba)sh code contribution to nsgminer if anyone wants to use it or if you want to refer/include for people.)

```
#!/bin/sh
#/usr/local/bin/nsgminer
# (Of course, such as on oldest GNU/Linux, you'd put this shell script in /usr/local/lib64.)
cd /usr/local/lib/nsgminer
exec /usr/local/lib/nsgminer/nsgminer "$@"
```
