### ISSUE TITLE
Help wanted! Testing purpose!

### ISSUE THREAD

**Issue by Saikatsaha1996** [ghostlander/nsgminer#46]
It possible to install without lpthread cancel program ?
If possible please help me!..

**Comment by ghostlander** [comment]
You can compile it with whatever threading library you want

**Comment by Saikatsaha1996** [comment]
> You can compile it with whatever threading library you want

Actually I want to compile it on android .. OpenCL found but getting error when I am running make.. because showing pthread can program null
