### ISSUE TITLE
Autogen.sh failed

### ISSUE THREAD

**Issue by Saikatsaha1996** [ghostlander/nsgminer#47]
![Screenshot_2022-05-07-21-54-20-900_com termux](https://user-images.githubusercontent.com/72664192/167263153-66912b86-4139-458d-8f2f-342fc3f5caed.jpg)

**Comment by ghostlander** [comment]
These submodules are SHA-256d FPGA bitstreams. They are not needed for NeoScrypt anyway, so you can comment out fetching of these submodules in autogen.sh

```
#if test -z "$NOSUBMODULES" ; then
#	echo 'Getting submodules...'
#	(
#		cd "${bs_dir}"
#		git submodule update --init
#	)
#fi

```

**Comment by Saikatsaha1996** [comment]
> These submodules are SHA-256d FPGA bitstreams. They are not needed for NeoScrypt anyway, so you can comment out fetching of these submodules in autogen.sh
> 
> ```
> #if test -z "$NOSUBMODULES" ; then
> #	echo 'Getting submodules...'
> #	(
> #		cd "${bs_dir}"
> #		git submodule update --init
> #	)
> #fi
> ```

Done building.. how to set intensity ?

**Comment by ghostlander** [comment]
> Done building.. how to set intensity ?

-I or --intensity on the command line

./nsgminer -h

**Comment by Saikatsaha1996** [comment]
> > Done building.. how to set intensity ?
> 
> -I or --intensity on the command line
> 
> ./nsgminer -h

Done .. but can you explain me why getting warning..

![Screenshot_2022-05-25-21-55-06-480_com termux](https://user-images.githubusercontent.com/72664192/170313463-1dd4b51c-0e83-41a3-b2cf-84e69d9ce3a2.jpg)

**Comment by Saikatsaha1996** [comment]
@ghostlander  hello sir! `requesting`
Can you add support `verushash` --algo for `CPU & GPU `

PLEASE requesting..

**Comment by ghostlander** [comment]
NSGminer doesn't support anything other than NeoScrypt on purpose. SHA-256d and Scrypt are legacy and not supported any more on CPUs, GPUs and FPGAs. They are present for historical and demonstrational purposes.

**Comment by Saikatsaha1996** [comment]
> NSGminer doesn't support anything other than NeoScrypt on purpose. SHA-256d and Scrypt are legacy and not supported any more on CPUs, GPUs and FPGAs. They are present for historical and demonstrational purposes.

Okay sir 😊
