### ISSUE TITLE
GPU address space pointer error

### ISSUE THREAD

**Issue by pilotniq** [ghostlander/nsgminer#7]
I've built nsgminer under Ubuntu 16.04, and when I run the benchmark for neoscrypt, I get the following errors at runtime:

void ScratchpadMix(void *X, const **global void *V, uchar idx)
                         ^
<kernel>:1314:22: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
                ScratchpadStore(V, X, i);
                                   ^
<kernel>:1268:46: note: passing argument to parameter 'X' here
void ScratchpadStore(__global void *V, void *X, uchar idx)
                                             ^
<kernel>:1322:17: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
                ScratchpadMix(X, V, idx);
                              ^
<kernel>:1274:26: note: passing argument to parameter 'X' here
void ScratchpadMix(void *X, const __global void *V, uchar idx)
                         ^
<kernel>:1372:24: warning: incompatible pointer types passing '__global ulong16
*__attribute**((address_space(16776963)))' to parameter of type '__global uint16
 *'
                if (i) SMix_Chacha(X,V); else SMix_Salsa(Z,V);
                                     ^
<kernel>:1309:48: note: passing argument to parameter 'V' here
void SMix_Chacha(uint16 X[4], __global uint16 *V)
                                               ^
<kernel[22:01:03] Failed to init GPU thread 0, disabling device 0

**Comment by ghostlander** [comment]
There is no ScratchpadMix() or ScratchpadStore() in NSGminer. These are from SGminer and its NeoScrypt kernel.
