### ISSUE TITLE
nsgminer.exe  command box with blinking cursor

### ISSUE THREAD

**Issue by jjziets** [ghostlander/nsgminer#8]
I am trying to run nsgminer.exe with this command

nsgminer.exe --api-listen -k neoscrypt -o stratum+ssl://hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64 

I only get a cmd window with the title  nsgminer.exe and a blinking cursor

running on windows 10 64 bit
amd driver 16.11.3
7 RX480 4GB

what can I do to get nsgminer to run?

If i run nsgminer.exe --benchmark  --neoscrypt it does start but not results.

**Comment by ghostlander** [comment]
The binaries were compiled without OpenSSL. Use stratum+tcp or recompile. --thread-concurrency is obsolete.

**Comment by jjziets** [comment]
Any why does the benchmark not work? 

I have try so far on Rx 480 cards, furyx, R9 390 and hd7990 

Different drivers also. 

Nothing.

**Comment by jjziets** [comment]
Pity that one can't edit comments to correct spelling mistakes. Met to say and why. Not any why

**Comment by ghostlander** [comment]
I don't use the integrated benchmarks. I test kernels in live environments. Although the reference NeoScrypt code has a set of CPU only benchmarks.

**Comment by jjziets** [comment]
I have tried nsgminer.exe --api-listen -k neoscrypt -o stratum+tcp://hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64

Still the same black screen on all my rigs.

Is there something that I need to instal to get it work on windows 7 and 10? clearly this is not an AMD driver or windows problem as I have tried numerous configurations.

**Comment by jjziets** [comment]
is there anouther pool i can try to test if the problem is not with pool?

**Comment by jjziets** [comment]
I got it to work. not sure what is the difference between the two

nsgminer.exe --api-listen -k neoscrypt -o stratum+tcp//hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64

vs 
nsgminer.exe --api-listen --neoscrypt -o stratum+tcp://hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64

bottom one works top one does not.

**Comment by ghostlander** [comment]
"-k neoscrypt" is no such option yet. "--neoscrypt" should be used instead.
